### ISSUE TITLE
Power Raspberry PI through it's own power port when UPS Lite is powered on

### ISSUE THREAD

**Issue by maxromanovsky** [linshuqin329/UPS-Lite#11]
Hi!
I haven't found it in manual, and want to clarify.
Is it okay if:
- UPS Lite is connected to Raspberry
- UPS Lite is turned on
- Charger is connected Raspberry PI own USB power port

Will I damage RPI or UPS Lite?

**Comment by linshuqin329** [comment]
I don't recommend this, this may damage the UPS-Lite，It is recommended that the Raspberry Pi is power supply only by UPS-Lite

**Comment by maxromanovsky** [comment]
Awesome, thanks!
