### ISSUE TITLE
Is there an official shop on Taobao 淘寶, AliExpress, or Amazon?

### ISSUE THREAD

**Issue by fumin** [linshuqin329/UPS-Lite#13]
I want to buy this great UPS-Lite, only from you the true creator, but I only use Taobao 淘寶, AliExpress, or Amazon.
What is your official shop on Taobao 淘寶, AliExpress, or Amazon?
Can you put it in the README?

我想從你的官方商店買 UPS-Lite，請問你在 淘寶, AliExpress, 或 Amazon的官方商店是甚麼?
可以把你的官方商店的連結 URL寫在 README裡面嗎?

**Comment by linshuqin329** [comment]
@fumin  this is my tindie store    https://www.tindie.com/products/rachel/ups-lite-for-raspberry-pi-zero/

**Comment by fumin** [comment]
Got it, will be using this store, thanks.
