### ISSUE TITLE
Power Adapter Unplug always

### ISSUE THREAD

**Issue by rknobbe** [linshuqin329/UPS-Lite#9]
Using UPS-Lite V1.2 on a Raspberry Pi Zero WH, GPIO input 4 is always low regardless of whether power is applied or not.

**Comment by ThatOneRoadie** [comment]
![image](https://user-images.githubusercontent.com/9691283/112528236-82c58f80-8d69-11eb-9f1f-fdaa5fecb006.png)
Pad 1 is open and will not show adapter plugged in until soldered together. 

![image](https://user-images.githubusercontent.com/9691283/112528333-a12b8b00-8d69-11eb-87dc-a7b46f0e9ad0.png)

**Comment by rknobbe** [comment]
Thanks!
